server:
  port: 8080

#H2 配置
spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    url: jdbc:h2:file:~/test
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  # H2 Console 配置
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      path: /h2-console
      enabled: true


  #jpa配置
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  # H2 Console 配置
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      path: /h2-console
      enabled: true

# coindeskUrl 寫入配置檔方便使用
coindesk:
  url: "https://kengp3.github.io/blog/coindesk.json"

